version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 12
      python: '3.8'

phases:
  build:
    commands:
      - 'yamlint ./*.yml'
      - 'npm run test-with-results'
reports:
 'arn:aws:codebuild:eu-west-3:610038518913:report-group/node':
    files:
    - './test-results.xml'
    file-format: 'JUNITXML'
'arn:aws:codebuild:eu-west-3:610038518913:report-group/coverage':
  base-derctory: 'coverage'
  files: 
  - 'icove report/**/*/'
  - 'clover.xml'
  file-format: 'CLOVERXML'
  
        

